<script lang="ts">
  import { base } from '$app/paths';
  import CodeBlock from '$lib/components/CodeBlock.svelte';
  import type { PageProps } from './$types';

  const { data }: PageProps = $props();

  const recipes: Array<{ num: string; title: string; body: string; pointer?: string }> = [
    {
      num: '01',
      title: 'Mail-merge: replace {{placeholders}} across the whole file',
      body: 'replaceTextEverywhere walks every story in the package — body, headers, footers, footnotes/endnotes, comments, textboxes — so a placeholder lurking in the page header is filled the same way a body one is.',
      pointer: 'samples/20-mailmerge-text-replace-*.docx (run `pnpm sample`)',
    },
    {
      num: '02',
      title: 'PowerPoint-style designed base',
      body: 'Open a hand-designed .docx with openDocx, merge its style table into your authoring graph with mergeStylesFromTemplate, then keep appending body content. The visual identity (fonts, colours, custom paragraph styles) carries over without any token-substitution dance.',
      pointer: 'samples/30-styled-base-*.docx',
    },
    {
      num: '03',
      title: 'Replace an image by alt text',
      body: 'replaceImageByAltText finds the inline image whose alt text matches and swaps the binary blob in-place. Rels and content types update transparently.',
      pointer: 'samples/23-mailmerge-image-replace-*.docx',
    },
    {
      num: '04',
      title: 'Tables of contents and field codes',
      body: 'addTableOfContents writes a Word-recognised TOC field with the current outline. appendField + WORD_FIELDS gives you PAGE / NUMPAGES / DATE / etc. without hand-rolling field XML.',
      pointer: 'integration tests under packages/core/src/integration.test.ts',
    },
    {
      num: '05',
      title: 'Tracked changes — accept or reject in bulk',
      body: 'acceptAllRevisions and rejectAllRevisions walk every w:ins / w:del / w:moveFrom / w:moveTo and resolve them. The ranges that disappear take their formatting markers with them.',
      pointer: 'samples/09-tracked-changes.docx',
    },
    {
      num: '06',
      title: 'Render in the browser with previewToDOM',
      body: 'previewToDOM accepts a Docx, Uint8Array, Blob, or ArrayBuffer and mounts a read-only render into a DOM container. Returns an idempotent Handle.dispose() for teardown.',
      pointer: 'see live in the playground',
    },
  ];
</script>

<svelte:head>
  <title>Recipes · word-kit</title>
</svelte:head>

<article class="prose">
  <p class="eyebrow">§ 02 · Recipes</p>
  <h1>Common scenarios, copy-paste ready.</h1>

  <p class="lede">
    Each recipe maps to a real test or a sample file generated by
    <code>pnpm sample</code>. Run the script to drop 32 demonstration
    <code>.docx</code> files into <code>./samples/</code> for inspection in Microsoft Word.
  </p>

  <ul class="recipe-list">
    {#each recipes as r (r.num)}
      <li class="recipe">
        <span class="r-num">{r.num}</span>
        <div class="r-body">
          <h3>{r.title}</h3>
          <p>{r.body}</p>
          {#if r.pointer}
            <p class="r-pointer"><span class="label">where:</span> <code>{r.pointer}</code></p>
          {/if}
        </div>
      </li>
    {/each}
  </ul>

  <h2>Browser embed (snippet)</h2>

  <p>
    Drop this into any Svelte / React / vanilla TS component. The lazy import keeps the
    preview package out of your initial bundle.
  </p>

  <CodeBlock html={data.previewEmbed.html} title={data.previewEmbed.path} coord="B1" />

  <p class="more">
    Want to see it run? <a href="{base}/playground">Open the playground</a>.
  </p>
</article>

<style>
  .prose {
    max-width: var(--max-content);
    margin: 0 auto;
    padding: 3rem 1.5rem 5rem;
  }

  h1 {
    font-family: var(--display);
    font-weight: 460;
    font-size: clamp(2rem, 4.6vw, 2.95rem);
    line-height: 1.05;
    letter-spacing: -0.026em;
    margin: 0 0 1rem;
    font-variation-settings: 'opsz' 144, 'SOFT' 30;
    max-width: 22ch;
  }

  .lede {
    color: var(--fg-soft);
    font-size: 1.06rem;
    line-height: 1.55;
    max-width: 64ch;
    margin: 0 0 2rem;
  }

  .recipe-list {
    list-style: none;
    padding: 0;
    margin: 0 0 2.5rem;
    border: 1px solid var(--border);
    border-radius: var(--radius);
    background: var(--bg-elev);
    overflow: hidden;
  }

  .recipe {
    display: grid;
    grid-template-columns: 4ch 1fr;
    gap: 1.25rem;
    padding: 1.15rem 1.4rem 1.25rem;
    border-bottom: 1px solid var(--border);
  }

  .recipe:last-child {
    border-bottom: none;
  }

  .r-num {
    font-family: var(--mono);
    font-size: 11.5px;
    color: var(--accent);
    font-weight: 500;
    letter-spacing: 0.06em;
    margin-top: 0.5rem;
  }

  .r-body h3 {
    margin: 0 0 0.4rem;
    font-family: var(--display);
    font-size: 1.15rem;
    font-weight: 540;
    font-variation-settings: 'opsz' 32, 'SOFT' 25;
  }

  .r-body p {
    margin: 0;
    color: var(--fg-soft);
    font-size: 0.95rem;
    line-height: 1.55;
  }

  .r-pointer {
    margin-top: 0.55rem !important;
    font-family: var(--mono);
    font-size: 11.5px;
    color: var(--fg-muted);
  }

  .r-pointer .label {
    text-transform: uppercase;
    letter-spacing: 0.12em;
    margin-right: 0.4rem;
    color: var(--fg-faint);
  }

  .more {
    margin-top: 2rem;
    border-top: 1px solid var(--border);
    padding-top: 1.25rem;
    color: var(--fg-soft);
    font-size: 0.95rem;
  }
</style>
